name: pkg_dio
description: Dio helper package
version: 0.0.1

environment:
  sdk: '3.9.2'

dependencies:
  dio: ^5.9.0
  #  dio_http2_adapter: ^2.5.1
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^9.0.5
  json_annotation: ^4.9.0
  logger: ^2.6.2
#  native_dio_adapter: ^1.4.0

dev_dependencies:
  build_runner: ^2.10.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
